Update ActiveUrlChecker.php
spatie/menu pull request #115
Opened 2020-09-16 15:54 UTC by Kibadda

A parent menu entry of a submenu does not get marked as active properly. This is most likely due to a wrong argument order in ActiveUrlChecker.php line 42:

```php
...
// If this url starts with the url we're matching with, it's active.
        if ($matchPath === $itemPath || Str::startsWith($matchPath, $itemPath)) {
            return true;
        }
...
```

should be

```php
...
// If this url starts with the url we're matching with, it's active.
        if ($matchPath === $itemPath || Str::startsWith($itemPath, $matchPath)) {
            return true;
        }
...
```

2020-09-30 22:01 UTC, freekmurze commented
Could you add a test to prove that this works?

2020-09-30 22:01 UTC, freekmurze requested changes
Please add a test

2020-12-01 11:08 UTC, mrk-j commented
I believe this isn't working, my PR #124 should fix this.

2020-12-01 21:25 UTC, freekmurze commented
Closing in favour of #124

2020-12-01 21:25 UTC, closed without merging