Add `id` attribute for menu
spatie/menu pull request #143
Opened 2023-03-08 13:52 UTC by milwad-dev

If you want to apply a series of animations etc. on the menu with JavaScript, this can be done much better by using ID.
Now this work is available and can be used easily.

```php
Menu::new()
    ->addId('navigation')
    ->add(Link::to('/', 'Home')->addId('home-link'))
    ->add(Link::to('/about', 'About'))
    ->add(Link::to('/contact', 'Contact'))
```

```html
<ul id="navigation">
    <li><a href="/" id="home-link">Home</a></li>
    <li><a href="/about">About</a></li>
    <li><a href="/contact">Contact</a></li>
</ul>
```

2023-03-09 12:19 UTC, sebastiandedeyne requested changes
An HTML element can only have one ID. Can the function signatures be modified to enforce this? (I posted some suggestions in the reviews)

Then we can add this in :)

2023-03-09 12:19 UTC, sebastiandedeyne commented on src/Html/Attributes.php
> +    protected array $ids = [];
An element can only have one ID.
```suggestion
    protected ?string $id = null;
```

2023-03-09 12:19 UTC, sebastiandedeyne commented on src/Html/Attributes.php
> +    public function addId(string | array $id): self
```suggestion
    public function id(?string $id): self
```

2023-03-09 12:19 UTC, sebastiandedeyne commented on src/Traits/HasHtmlAttributes.php
> +    public function addId(string $id): static
```suggestion
    public function id(?string $id): static
```

2023-03-09 12:19 UTC, sebastiandedeyne commented on src/Traits/HasParentAttributes.php
> +    public function addParentId(string $id): static
```suggestion
    public function parentId(?string $id): static
```

2023-03-10 06:07 UTC, milwad-dev commented
@sebastiandedeyne 
Right, I forgot this point!

2023-03-10 18:00 UTC, sebastiandedeyne approved these changes

2023-03-10 18:01 UTC, merged